name: Build and deploy container app to Azure Web App - orcamentogenericofrontend

on:
  push:
    branches:
      - primeiroMvp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mcr.microsoft.com/
          username: moises
          password: moises

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mcr.microsoft.com/moises/appsvc/staticsite:${{ github.sha }}
          file: ./Dockerfile

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'orcamentogenericofrontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ea9492f6852a4950a6a37112a7bfea0b }}
          images: 'mcr.microsoft.com/moises/appsvc/staticsite:${{ github.sha }}'
