name: Build and Deploy

on:
  push:
    branches:
      - primeiroMvp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Build and Deploy
      run: |
        sudo cp -r /var/www/frontend_ic/* https://github.com/moisesneto23/servico-orcamento-generico-frontend/dist

