#name: Build and Deploy

#on:
 # push:
  #  branches:
   #   - primeiroMvp

#jobs:
 # build:
  #  runs-on: ubuntu-latest

   # steps:
    #- name: Checkout Repository
    #  uses: actions/checkout@v3


    #- name: Build and Deploy
     # run: |
      #  sudo cp -r /var/www/servico-orcamento-generico-frontend/* https://github.com/moisesneto23/servico-orcamento-generico-frontend/

