#name: Build and Deploy

on:
  push:
    branches:
    - primeiroMvp

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: 18.
    - name: run instal, build
      run: |
        npm install
        npm run build


    #- name: Build and Deploy
     # run: |
      #  sudo cp -r /var/www/servico-orcamento-generico-frontend/* https://github.com/moisesneto23/servico-orcamento-generico-frontend/

