# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - orcamentogenericofrontend

on:
  push:
    branches:
      - primeiroMvp
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_80972a737dfa480bb4e368710fb05da2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f2c1b86953141448e3a60c444785701 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_80972a737dfa480bb4e368710fb05da2 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'orcamentogenericofrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1aea231237404d6aabcccb181877027b }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_80972a737dfa480bb4e368710fb05da2 }}/appsvc/staticsite:${{ github.sha }}'